spring:
  config:
    activate:
      on-profile: "test"

build:
  version: "1.0"

cards:
  message: "Welcome to cards service test configuration local APIs "
  contactDetails:
    name: "Bao Pen - Developer"
    email: "baopena@gmail.com"
  calls:
    - (555) 555-1234
    - (555) 523-1345

# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true
#     url: /openapi.yml