spring:
  application:
    name: ${APP_NAME:cards}

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active:
      - "default"

  config:
    import:
      - "application-prod.yml"
      - "application-test.yml"

  build:
    version: "3.0"

cards:
  message: "Welcome to cards service default configuration local APIs "
  contactDetails:
      name: "Bao Pen - Developer"
      email: "baopena@gmail.com"
  calls:
      - (555) 555-1234
      - (555) 523-1345

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi.yml