spring:
  application:
    name: ${APP_NAME:cards}
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always   # Spring Boot always execute SQL initialization scripts at resources forlder
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "refresh"