spring:
  application:
    name: ${APP_NAME:cards}

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    activate:
      on-profile: "test"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi.yml