spring:
  application:
    name: ${APP_NAME:loans}
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always  # Spring Boot always execute SQL initialization scripts at resources forlder
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "busrefresh"