spring:
  application:
    name: ${APP_NAME:loans}

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
  config:
    import:
      - "application-prod.yml"
      - "application-test.yml"

  profiles:
    active: "default"

  build:
    version: "3.0"

loans:
  message: "Welcome to loans service default configuration local APIs "
  contactDetails:
    name: "Bao Pen - Developer"
    email: "baopena@gmail.com"
  calls:
    - (555) 555-1234
    - (555) 523-1345

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi.yml