spring:
  config:
    activate:
      on-profile: "test"


build:
  version: "1.0"

accounts:
  message: "Welcome to accounts service default configuration test APIs "
  contactDetails:
    name: "Bao Pen - Developer"
    email: "baopena@gmail.com"
  calls:
    - (555) 555-1234
    - (555) 523-1345