
name: CI workflow for java with maven

# define github events: when to run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     
jobs:
  # define jobs: what to do
  build:
    # define runners: where to run
    runs-on: ubuntu-latest

    # define sequence of tasks as part of job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: specify jdk version
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distributrion: 'termurin'
          architecture: x64

      - name: Build all modules
        run: mvn --batch-mode --update-snapshots verify
