name: CI pipeline for loans servie

 # define GitHub action events:  define when to run
on: 
  push:
    branches: ["main"]
    paths:
    - 'loans/**'

  pull_request:
    branches: ["main"]
    paths: 
    - 'loans/**'

  # this allows you to trigger the workflow manually
  workflow_dispatch:




# define GitHub action jobs: define what to do
jobs:
  build:
  # define GitHub actions runner: define where to run
    runs-on: ubuntu-latest

  # define sequence of tasks as part of the job
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: specify jdk
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          architecture: "x64"

      - name: build the service
        run: mvn --batch-mode  --update-snapshots verify
        working-directory: ./loans

